# Group by and Aggregating

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\USER\Documents\Pandas Tutor\world_population_excel_workbook.xlsx")

In [3]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [6]:
group_by_frame =df.groupby('Continent')

In [9]:
df.groupby('Continent').mean(numeric_only=True)

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,
Africa,92.157895,2.503037e+07,2.387144e+07,2.107197e+07,1.851277e+07,1.436747e+07,1.119563e+07,8.448007e+06,6.411304e+06,5.318941e+05,125.047646,1.021244,0.313509
Asia,77.560000,9.442767e+07,9.326173e+07,8.916500e+07,8.440083e+07,7.470179e+07,6.421127e+07,5.270668e+07,4.289813e+07,6.427628e+05,1025.024136,1.009384,1.183800
Europe,124.500000,1.486295e+07,1.491584e+07,1.483071e+07,1.471228e+07,1.452187e+07,1.440642e+07,1.385054e+07,1.311848e+07,4.602082e+05,663.324742,1.002256,0.186600
North America,160.925000,1.500740e+07,1.485591e+07,1.425960e+07,1.356802e+07,1.215174e+07,1.053166e+07,9.207334e+06,7.885865e+06,6.061044e+05,272.761758,1.004175,0.187750
Oceania,188.521739,1.958198e+06,1.910149e+06,1.756664e+06,1.613164e+06,1.357512e+06,1.162775e+06,9.965322e+05,8.469683e+05,3.702209e+05,132.543065,1.007383,0.023913
South America,97.571429,3.120119e+07,3.082357e+07,2.950960e+07,2.807702e+07,2.497388e+07,2.122474e+07,1.727064e+07,1.378194e+07,1.273813e+06,20.971979,1.007957,0.391429

In [11]:
df.groupby('Continent').count()

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Africa,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57
Asia,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50
Europe,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50
North America,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Oceania,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
South America,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14

In [12]:
df.groupby('Continent').min()

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Africa,6,AGO,Algeria,Abuja,107118,105530,99240,92409,80060,71057,52233,35383,374,2.1654,1.0004,0.00
Asia,1,AFG,Afghanistan,Abu Dhabi,449002,441725,421437,361575,282507,224957,164887,118007,30,2.1727,0.9816,0.01
Europe,9,ALB,Albania,Amsterdam,510,520,564,596,651,700,733,752,1,3.6204,0.9120,0.00
North America,3,ABW,Anguilla,Basse-Terre,4390,4500,5059,4938,5138,5168,2983,2417,21,0.0261,0.9937,0.00
Oceania,55,ASM,American Samoa,Alofi,1871,1827,1454,1367,1666,1669,1647,1714,12,3.4032,0.9831,0.00
South America,7,ARG,Argentina,AsunciÃ³n,3780,3747,3408,3187,3080,2332,2240,2274,12173,0.3105,0.9990,0.00

In [14]:
df.groupby('Continent').sum(numeric_only=True)

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,
Africa,5253,1426730932,1360671810,1201102442,1055228072,818946032,638150629,481536377,365444348,30317963,7127.7158,58.2109,17.87
Asia,3878,4721383274,4663086535,4458250182,4220041327,3735089604,3210563577,2635334228,2144906290,32138141,51251.2068,50.4692,59.19
Europe,6225,743147538,745792196,741535608,735613934,726093423,720320797,692527159,655923991,23010411,33166.2371,50.1128,9.33
North America,6437,600296136,594236593,570383850,542720651,486069584,421266425,368293361,315434606,24244178,10910.4703,40.1670,7.51
Oceania,4336,45038554,43933426,40403283,37102764,31222778,26743822,22920240,19480270,8515081,3048.4905,23.1698,0.55
South America,1366,436816608,431530043,413134396,393078250,349634282,297146415,241789006,192947156,17833382,293.6077,14.1114,5.48

In [15]:
df.groupby('Continent').agg({'2022 Population': ['mean','max','count','sum']})

              2022 Population
                         mean         max count         sum
Continent
Africa           2.503037e+07   218541212    57  1426730932
Asia             9.442767e+07  1425887337    50  4721383274
Europe           1.486295e+07   144713314    50   743147538
North America    1.500740e+07   338289857    40   600296136
Oceania          1.958198e+06    26177413    23    45038554
South America    3.120119e+07   215313498    14   436816608